name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas=1.2.3
  - pytest=6.2.2
  - scipy=1.5.2
  - pip=23.3.1
  - pip:
      - mlflow==1.14.1
      - wandb==0.16.0
      - protobuf==3.20.3
