name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - hydra-core=1.3.2
  - matplotlib=3.6.0
  - pandas=1.2.3
  - pip=23.3.1
  - scikit-learn=1.3.2
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
